version: '3.5'
 
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/dahln/data/db:/data/db
    restart: always

  app:
    image: damnstack/stack:stack_app.4.0.0
    links:
      - db
    restart: always

  nginx:
    image: damnstack/stack:stack_nginx.4.0.0
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    restart: always