version: '3.5'
 
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/dahln/data/db:/data/db
    restart: always

  api:
    image: dahln/damn:damn_api.5.0.0
    links:
      - db
    restart: always

  nginx:
    image: dahln/damn:damn_proxy.5.0.0
    links:
      - api
    ports:
      - "80:80"
      - "443:443"
    restart: always