version: '3.5'
 
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always

  api:
    image: dahln/damn-deploy:damn_api.rpi.1
    links:
      - db
    restart: always

  nginx:
    image: dahln/damn-deploy:damn_proxy.rpi.1
    links:
      - api
    ports:
      - "80:80"
      - "443:443"
    restart: always